sonar.projectKey=android-project-auto-scan
sonar.projectName=Android App Codebase
sonar.projectVersion=1.0
sonar.sourceEncoding=UTF-8
sonar.sources=src/main/java,src/main/kotlin,app/src/main/java,app/src/main/kotlin
sonar.tests=src/test/java,src/test/kotlin,app/src/test/java,app/src/test/kotlin,app/src/androidTest/java
sonar.java.binaries=build/intermediates/javac/debug/classes,app/build/intermediates/javac/debug/classes,build/classes/kotlin/debug,app/build/classes/kotlin/debug
sonar.exclusions=**/build/**,**/.gradle/**,**/R.java,**/BuildConfig.java,**/*_ViewBinding*.*,**/Dagger*.*,**/*Hilt*.*,**/*_Factory*.*
